# Generated by Django 5.2.5 on 2025-09-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dimensiones',
            field=models.CharField(help_text='Formato: alto x largo x ancho', max_length=100, verbose_name='Dimensiones (cm)'),
        ),
    ]
