# Generated by Django 5.2.9 on 2025-12-03 02:15

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_historicalbrand_historicalcategory_historicalproduct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                upload_to=api.models.upload_location, verbose_name="Imagen"
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Cantidad")),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("IN", "Entrada"),
                            ("OUT", "Salida"),
                            ("ADJUST", "Ajuste Negativo/Pérdida"),
                        ],
                        max_length=10,
                        verbose_name="Tipo de Movimiento",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="Motivo")),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="api.product",
                        verbose_name="Producto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de Stock",
                "verbose_name_plural": "Movimientos de Stock",
                "ordering": ["-timestamp"],
            },
        ),
    ]
