# Generated by Django 5.2.1 on 2025-12-07 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo / Visible'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo / Visible'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='api.product', verbose_name='Producto'),
        ),
    ]
