# Generated by Django 5.2.1 on 2025-12-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_historicalproduct_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa / Visible'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa / Visible'),
        ),
        migrations.AddField(
            model_name='historicalbrand',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa / Visible'),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa / Visible'),
        ),
        migrations.AddField(
            model_name='historicalprovider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa / Visible'),
        ),
        migrations.AddField(
            model_name='provider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activa / Visible'),
        ),
    ]
